[project]
name = "tunely"
version = "0.1.0"
description = "Music Downloader"
requires-python = ">=3.13"
dependencies = [
    "librespot",
]

[tool.uv.sources]
librespot = { git = "https://github.com/kokarare1212/librespot-python" }
